company/urls.py
from django.urls import path
from .views import CompanyInfoView

app_name = 'company'

urlpatterns = [
    path('company/<int:pk>/', CompanyInfoView.as_view(), name='company_info'),
]


settings/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
  path('admin/', admin.site.urls),
  path('shop/', include('shop.urls', namespace='shop')),
  path('', RedirectView.as_view(url='shop/', permanent=True)),
  path('company/', include('company.urls', namespace='company')),
  path('user/', include('user.urls', namespace='user')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +\
              static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/urls.py
from django.contrib.auth.decorators import permission_required
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import IndexView, CreateProductView, DeleteProductView

app_name = 'shop'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('create-product/', CreateProductView.as_view(), name='create_product'),
    path('delete-product/<int:pk>/', permission_required('change-post', login_url='user:login')(
        DeleteProductView.as_view()),
         name='delete_product'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import SignUp, UserLogin, LogoutView, PersonalArea, UpdateUser, DeleteUser

app_name = 'user'

urlpatterns = [
    path('registration/', SignUp.as_view(), name='registration'),
    path('login/', UserLogin.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('user/', PersonalArea.as_view(), name='personal_area'),
    path('user-update/<int:pk>/', UpdateUser.as_view(), name='update_user'),
    path('user-delete/<int:pk>/', DeleteUser.as_view(), name='delete_user'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

company/models.py
from django.core.validators import validate_image_file_extension
from django.db import models
from core.models import Core


class Category(models.Model):
    title = models.CharField(max_length=50, blank=False, verbose_name='Тип компании')

    class Meta:
        verbose_name = 'Тип компании'
        verbose_name_plural = 'Типы компаний'

    def __str__(self) -> str:
        return f'{self.title}'


class Company(Core):
    image = models.ImageField(upload_to='company/image', validators=[
        validate_image_file_extension], verbose_name='картинка', blank=True)
    category = models.ManyToManyField(Category, verbose_name='Категория')

    def __str__(self) -> str:
        return f'{self.title}'

    class Meta:
        verbose_name = 'Компания'
        verbose_name_plural = 'Компании'

core/models.py
from django.db import models


class Core(models.Model):
    title = models.CharField(max_length=1000, verbose_name="название", unique=True)
    is_active = models.BooleanField(default=True, verbose_name='Опубликован')
    id = models.AutoField(primary_key=True, unique=True, verbose_name='id')
    description = models.CharField(max_length=50, verbose_name='описание')

    def __str__(self) -> str:
        return f'{self.title}'

    class Meta:
        abstract = True


settings/core/models.py
from django.db import models


class Core(models.Model):
    title = models.CharField(max_length=1000, verbose_name="название")
    is_active = models.BooleanField(default=True, verbose_name='Опубликован')

    def __str__(self) -> str:
        return self.title

    class Meta:
        abstract = True

shop/models.py
from django.core.validators import validate_image_file_extension
from django.db import models
from core.models import Core
from company.models import Company


class Category(models.Model):
    title = models.CharField(max_length=50, blank=False, unique=True,  verbose_name='Категория '
                                                                                    'товара')

    class Meta:
        verbose_name = 'Категория товара'
        verbose_name_plural = 'Категории товаров'

    def __str__(self) -> str:
        return f'{self.title}'


class Product(Core):
    image = models.ImageField(upload_to='product/image', validators=[
        validate_image_file_extension], verbose_name='картинка', blank=False)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, verbose_name='Компания',
                                null=True)
    category = models.ManyToManyField(Category, verbose_name='Категория')
    price = models.IntegerField(default=30, blank=False, null=False)

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукция'

    def __str__(self) -> str:
        return f'{self.title}'

user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from core.models import Core


class CustomUser(AbstractUser):
    id = models.AutoField(primary_key=True, unique=True, verbose_name='id')
    username = models.CharField(max_length=30, unique=True, null=False, verbose_name='Логин',
                                error_messages={'unique': "Такой пользователь уже существует!"})
    avatar = models.ImageField(upload_to='user/avatars/', verbose_name='Аватарка', null=True,
                               blank=True)
    description = models.CharField(max_length=50, null=True, blank=True, verbose_name='описание')

    def __str__(self):
        return self.username

shop/forms.py
from django import forms
from .models import Product


class CreateProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ('title', 'description', 'image',
                  'company', 'category', 'price')

user/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms

from user.models import CustomUser


class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'avatar', 'description')


class UserUpdateForm(forms.ModelForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'description',  'avatar',)

company/views.py
from django.views.generic import DetailView
from .models import Company


class CompanyInfoView(DetailView):
    model = Company
    queryset = Company.objects.filter(is_active=True)
    template_name = 'company/company_info.html'

core/views.py
from django.shortcuts import render

# Create your views here.

shop/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DeleteView
from .forms import CreateProductForm
from .models import Product


class IndexView(ListView):
    model = Product
    template_name = 'index.html'


class CreateProductView(LoginRequiredMixin, CreateView):
    login_url = 'user:login'
    model = Product
    template_name = 'shop/create_product.html'
    form_class = CreateProductForm
    success_url = reverse_lazy('user:personal_area')


class DeleteProductView(DeleteView):
    model = Product
    success_url = reverse_lazy('shop:index')

    def form_valid(self):
        self.object.delete()




user/views.py
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import ListView, UpdateView, DeleteView
from user.forms import UserRegistrationForm, UserUpdateForm
from user.models import CustomUser


class UserLogin(LoginView):
    """Класс входа"""
    template_name = 'user/login.html'

    def get_success_url(self):
        return reverse_lazy('shop:index')


class LogoutView(View):
    """Класс выхода"""
    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('shop:index'))


templates/company/company_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'company/company_info.css' %}">
</head>
<body>

<div class="sidenav">
    <a href="{% url 'shop:index' %}">Домашняя страница</a>
    {% if user.is_authenticated %}
        <a href="{% url 'user:personal_area' %}">Личный кабинет: {{ request.user.username }}</a>
        <a href="{% url 'user:logout' %}">Выход</a>
    {%else%}
        <a href="{% url 'user:login' %}">Вход</a>
        <a href="{% url 'user:registration' %}">Регистрация</a>
    {%endif%}
</div>
{% block content %}

            <div class="post-wrap">
                <div class="post-item">
                    <div class="item-content">
                        <div class="item-icon group">
                            <p>Название: {{ company.title }} </p>
                            {% if company.image %}
                                <img src="{{ company.image.url}}" alt="connect" style="max-height:150px">
                            {% endif %}
                            <p>Описание: {{ company.description }}</p>
                            <p>Категория компании:{% for category in company.category.all %}
                                        {# выводим m2m#}
                                {{ category.title }},{% endfor %}</p>
                        </div>
                    </div>
                </div>
            </div>

{% endblock %}
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'shop/index.css' %}">
</head>
<body>

<div class="sidenav">
    <a href="#">Домашняя страница</a>
    {% if user.is_authenticated %}
    <a href="{% url 'user:personal_area' %}">Личный кабинет: {{ request.user.username }}</a>
    <a href="{% url 'shop:create_product' %}">Создание продукта</a>
    <a href="{% url 'user:logout' %}">Выход</a>
    {%else%}
    <a href="{% url 'user:login' %}">Вход</a>
    <a href="{% url 'user:registration' %}">Регистрация</a>
    {%endif%}
</div>
{% block content %}
    {% if product_list %}
        {% for product in product_list %}
            {% if request.user.is_staff %}
                <div class="post-wrap">
                    <div class="post-item">
                        <div class="item-content">
                            <div class="item-icon group">
                                <p>Название: {{ product.title }} </p>
                                <img src="{{ product.image.url}}" alt="connect" style="max-height:150px">
                                <p>Описание: {{ product.description }}</p>
                                <p>Категория тавара:{% for category in product.category.all %}
                                    {# выводим m2m#}
                                    {{ category.title }},{% endfor %}</p>
                                <p><a href="{% url 'company:company_info' product.company_id  %}">
                                    Компания производитель: {{ product.company }}</a></p>
                                <p>Цена: {{ product.price }} руб</p>
                                {% if request.user.is_staff %}
                                    <p><a href="{% url 'shop:delete_product' product.id %}">
                                        <strong>Удалить продукт?</strong></a></p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            {% else %}
                {% if product.is_active != False %}
                    <div class="post-wrap">
                        <div class="post-item">
                            <div class="item-content">
                                <div class="item-icon group">
                                    <p>Название: {{ product.title }} </p>
                                    <img src="{{ product.image.url}}" alt="connect" style="max-height:150px">
                                    <p>Описание: {{ product.description }}</p>
                                    <p>Категория тавара:{% for category in product.category.all %}
                                        {# выводим m2m#}
                                        {{ category.title }},{% endfor %}</p>
                                    <p><a href="{% url 'company:company_info' product.company_id  %}">
                                        Компания производитель: {{ product.company }}</a></p>
                                    <p>Цена: {{ product.price }} руб</p>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endif %}
        {% endfor %}
    {% endif %}
{% endblock %}

</body>
</html>

templates/shop/create_product.html
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
    <lang></lang>
    <meta charset="utf-8">
    <title>Регистрация</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="stylesheet" href="{% static 'shop/create_product.css' %}">
</head>
<body>

<div class="container">
    <h1>Создание продукта</h1>
    <p>Следуйте форме</p>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="w-100 btn btn-lg btn-primary" type="submit" value="создать">
    </form>
</div>
</div>
</body>
</html>

templates/shop/product_confirm_delete.html
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
    <lang></lang>
    <meta charset="utf-8">
    <title>Регистрация</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="stylesheet" href="{% static 'shop/delete_product.css' %}">
</head>
<body>

<div class="container">
    <h1>Удаление Продукта</h1>
    <p>Вы уверены, что хотите удалить продукт: {{ product.title }}?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Удалить</button>
    </form>
</div>
</div>
</body>
</html>

templates/user/customuser_confirm_delete.html
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
    <lang></lang>
    <meta charset="utf-8">
    <title>Регистрация</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="stylesheet" href="{% static 'user/delete_user.css' %}">
</head>
<body>

<div class="container">
    <h1>Удаление профиля</h1>
    <p>Вы уверены, что хотите удалить профиль: {{ request.user.username }}?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Удалить</button>
    </form>
</div>
</div>
</body>
</html>

templates/user/login.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    {% load static %}
    <link rel="stylesheet" href="{% static 'user/login.css' %}">
    <title>Login</title>
</head>
<body class="text-center">
<div class="container">
    <h1>Вход</h1>
    <p>Следуйте этой форме</p>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="w-100 btn btn-lg btn-primary" type="submit" value="Вход">
    </form>
</div>
</body>
</html>

templates/user/personal_area.html
<!doctype html>
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="stylesheet" href="{% static 'user/personal_area.css' %}">
    {%block title%} <title>Дизайн студия</title> {%endblock%}
</head>
<body>
<div class="sidenav">
    <a href="{% url 'shop:index' %}">Домашняя страница</a>
    {% if user.is_authenticated %}
        <a href="#">Личный кабинет: {{ request.user.username }}</a>
        <a href="{% url 'user:logout' %}">Выход</a>
    {%else%}
        <a href="{% url 'user:login' %}">Вход</a>
        <a href="{% url 'user:registration' %}">Регистрация</a>
    {%endif%}
</div>

<div class="post-wrap">
    <div class="post-item">
        <div class="item-content">
            <div class="item-icon group">
                {% if user.avatar %}
                    <img src="{{ request.user.avatar.url }}" alt="connect" style="max-height:150px">
                {% endif %}
            </div>
            <div class="item-body">
                <h3>Имя: {{ user.username }}</h3>
                {% if user.avatar %}
                    <h3>Описание профиля: {{ user.description }}</h3>
                {% endif %}
                <p><a href="{% url 'user:update_user' user.id %}">
                    <strong>Изменить профиль?</strong></a></p>
                <p><a href="{% url 'user:delete_user' user.id %}">
                    <strong>Удалить профиль?</strong></a></p>
            </div>
            <div class="item-footer">
            </div>
        </div>
    </div>
</div>
</body>
</html>

templates/user/register.html
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
    <lang></lang>
    <meta charset="utf-8">
    <title>Регистрация</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="stylesheet" href="{% static 'user/register.css' %}">
</head>
<body>

<div class="container">
    <h1>Регистрация</h1>
    <p>Следуйте форме</p>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="w-100 btn btn-lg btn-primary" type="submit" value="Регистрация">
    </form>
</div>
<div class="container signin">
    <p>У вас уже есть аккаунт? <a href="{% url 'user:login' %}">Вход</a>.</p>
</div>
</body>
</html>

templates/user/update_user.html
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
    <lang></lang>
    <meta charset="utf-8">
    <title>Регистрация</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="stylesheet" href="{% static 'user/register.css' %}">
</head>
<body>

<div class="container">
    <h1>Регистрация</h1>
    <p>Следуйте форме</p>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="w-100 btn btn-lg btn-primary" type="submit" value="login">
    </form>
</div>
<div class="container signin">
    <p>У вас уже есть аккаунт? <a href="{% url 'user:login' %}">Вход</a>.</p>
</div>
</body>
</html>